### ISSUE TITLE
Problem when adding items to vendors

### ISSUE THREAD

**Issue by ryanch94** [mangosArchives/Mangos-Zero-server-old#18]
So I've made a few custom vendors in map 13(can't remember the name of it. Basically the giant box) and when I'm adding items to the vendor a lot of the items don't show in the list of items that the vendor is selling even though they are in the database. I think it's a core bug or I may have the NPC flag wrong could you possibly check this out?

**Comment by ghost** [comment]
How did you add the items? Fixed additions or using templates? Did you set the vendor flags appropriatly?

**Comment by ryanch94** [comment]
using the .npc additem command. I used the same flags as an armor vendor in SW. The items I'm trying to add are items from raid sets. Funny thing is the warrior items add fine everything else doesn't though.

**Comment by Nanaki52** [comment]
If the items are class-specific, you can only see those useable by your class. If you are a Warrior you will only see Warrior sets, and so on. Log in with a GM account to see every item for every class.
