### ISSUE TITLE
[Core/Pet] Broken Tooth as tamed issue with attackspeed

### ISSUE THREAD

**Issue by coffzor** [mangosArchives/Mangos-Zero-server-old#35]
Broken tooth is supposed to have 1.0 in attackspeed before and after being tamed.

"Broken Tooth was once considered the ultimate hunter pet mostly for his capabilities in PvP combat. He was sought after for his 1.0 attack speed, which was the quickest in the game. However, since pet speed normalization in patch 2.0.1 he has lost this ability and is no longer considered a pet to strive for."

Source: http://www.wowwiki.com/Broken_Tooth

**Comment by coffzor** [comment]
I think theres something written in the core to "normalize" pet speed since mangoszero is a backport. So look into this since this is a big feature of vanilla!

Edit: This will also make hunters to become playable under vanilla. How it is now, they're pretty useless except for tanq shot.

**Comment by khamarr3524** [comment]
I've just recently gotten back into MaNGOS development, and will be looking into this as Vanilla is my favorite version! Will get back to you if I find something.

**Comment by Salja** [comment]
the zero repo have moved thats here is all old check this https://github.com/mangoszero
