### ISSUE TITLE
[FIX] Take ammo for most ranged spells

### ISSUE THREAD

**Issue by sidsukana** [mangosArchives/Mangos-Zero-server-old#5]
Now ammo takes only Multishot, Autoshot and Aimed Shot. I think it's wrong. I propose to make this piece of code move to Spell::cast () function, after TakeReagents (). Your opinion?

I think for mangos-one actualy too...

http://pastebin.com/V5Uf2ZzR

**Comment by KuraiNeko** [comment]
I recommed add this part of code to dev branch.
It fix very ugly hack wiht hunters attack.

**Comment by sidsukana** [comment]
Commited to develop branch

**Comment by KuraiNeko** [comment]
So. We should close issue i think.
After several tests All devs part shoul be applien in master.
