### ISSUE TITLE
Diminishing

### ISSUE THREAD

**Issue by KuraiNeko** [mangosArchives/Mangos-Zero-server-old#6]
Few commits earlier diminishing  was deleted from core.
Frost shock\nova\ench roots.
It's happaned by some incorrect information reason added to Vlad.

Diminishing sjould be returned in to core now!!

**Comment by sidsukana** [comment]
Confirmed.

**Comment by Salja** [comment]
i can not find this commit

**Comment by sidsukana** [comment]
Commit when Vladimir or Yehonal moved diminishing code to Mods.

**Comment by KuraiNeko** [comment]
Sid. Maybe you commit this part?

**Comment by sidsukana** [comment]
[z1796]
Now i think may remove diminishing code from mods.)

**Comment by KuraiNeko** [comment]
close
